name: FYS_STK_env
channels:
  - conda-forge
dependencies:
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - numpy=2.1.0
  - pandas=2.2.2
  - pillow=10.4.0
  - pip=24.2
  - python=3.12.5
  - scikit-learn=1.5.1
  - scipy=1.14.1
  - imageio=2.35.1
